version: '3'
services:
  mongo_botmyshop:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_botmyshop:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_botmyshop: